"""String templates used by ``generate_tasks.py``."""

# Module-level header for the generated ``src/inspect_harbor/_tasks.py``.
# The ``{functions}`` placeholder is filled with the concatenation of
# ``PACKAGE_TASK_TEMPLATE`` instances.
TASKS_TEMPLATE = '''# ruff: noqa: D205, D400, D401, D403, D404
"""Harbor registry dataset tasks.

This file is auto-generated by scripts/generate_tasks.py.
Do not edit manually.

Registry: https://hub.harborframework.com/datasets
"""

from inspect_ai import Task, task

from inspect_harbor._harbor.task import harbor as _harbor_base

{functions}
'''

# Per-task block for a hub-published Harbor dataset. Defaults to ``ref="latest"``.
PACKAGE_TASK_TEMPLATE = '''
@task
def {func_name}(
    ref: str = "latest",
    dataset_task_names: list[str] | None = None,
    dataset_exclude_task_names: list[str] | None = None,
    n_tasks: int | None = None,
    overwrite_cache: bool = False,
    sandbox_env_name: str = "docker",
    override_cpus: int | None = None,
    override_memory_mb: int | None = None,
    override_gpus: int | None = None,
) -> Task:
    r"""{description}

    Slug: {package_name}
    Latest digest: {resolved_version}
    """
    return _harbor_base(
        package_name="{package_name}",
        package_ref=ref,
        dataset_task_names=dataset_task_names,
        dataset_exclude_task_names=dataset_exclude_task_names,
        n_tasks=n_tasks,
        overwrite_cache=overwrite_cache,
        sandbox_env_name=sandbox_env_name,
        override_cpus=override_cpus,
        override_memory_mb=override_memory_mb,
        override_gpus=override_gpus,
    )
'''

# Header for the generated listing data file. ``docs/registry.qmd`` itself
# is hand-maintained; only ``docs/registry-listing.yml`` is regenerated.
REGISTRY_YML_HEADER = """# This file is auto-generated by scripts/generate_tasks.py. Do not edit manually.
#
# Feeds the Quarto listing on docs/registry.qmd.
#
# Source of truth: scrape of hub.harborframework.com/datasets +
#   PackageDatasetClient.get_dataset_metadata for each slug.
# Categories: docs/overrides.yml (hand-maintained; see file header).
"""

# Per-page ``.qmd`` body for ``docs/registry/<func_name>.qmd``. The
# dataset-information table rows are pre-rendered by the caller.
PAGE_TEMPLATE = """---
title: "{title}"
description: |
  {description}
{categories_block}---

[← Back to Registry](../registry.qmd)

## Run this task

**CLI:**

```bash
inspect eval inspect_harbor/{func_name} --model openai/gpt-5
```

**Python:**

```python
from inspect_ai import eval
from inspect_harbor import {func_name}

eval({func_name}(), model="openai/gpt-5")
```

## Dataset information

| | |
|---|---|
{table_rows}

See [Task Parameters](../parameters.qmd) for the parameter set shared across all Harbor tasks.
"""
