#!/usr/bin/env python3
"""Generate static task functions from Harbor registry.

This script fetches the Harbor registry and generates tasks.py with all
dataset-specific task functions.
"""

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from urllib.request import urlopen

REGISTRY_URL = "https://raw.githubusercontent.com/laude-institute/harbor/refs/heads/main/registry.json"
TASKS_FILE = Path(__file__).parent.parent / "src" / "inspect_harbor" / "tasks.py"
TASKS_TEMPLATE = '''"""Harbor registry dataset tasks.

This file is auto-generated by scripts/generate_tasks.py.
Do not edit manually.

Last updated: {timestamp}
Registry: {registry_url}
"""

from inspect_ai import Task, task

from inspect_harbor.harbor._task import harbor as _harbor_base

{functions}
'''
TASK_FUNCTION_TEMPLATE = '''
@task
def {func_name}(
    dataset_task_names: list[str] | None = None,
    dataset_exclude_task_names: list[str] | None = None,
    n_tasks: int | None = None,
    overwrite_cache: bool = False,
    sandbox_env_name: str = "docker",
    override_cpus: int | None = None,
    override_memory_mb: int | None = None,
    override_gpus: int | None = None,
) -> Task:
    r"""{description}

    Dataset: {dataset_name}
    {version_info}
    """
    return _harbor_base(
        dataset_name_version="{dataset_name_version}",
        dataset_task_names=dataset_task_names,
        dataset_exclude_task_names=dataset_exclude_task_names,
        n_tasks=n_tasks,
        overwrite_cache=overwrite_cache,
        sandbox_env_name=sandbox_env_name,
        override_cpus=override_cpus,
        override_memory_mb=override_memory_mb,
        override_gpus=override_gpus,
    )
'''


def fetch_registry() -> list[dict[str, Any]]:
    """Fetch the Harbor registry JSON."""
    print(f"Fetching registry from {REGISTRY_URL}...")
    with urlopen(REGISTRY_URL, timeout=10) as response:
        return json.loads(response.read().decode())


def dataset_name_to_function_name(dataset_name_version: str) -> str:
    """Convert dataset name or name@version to valid Python function name.

    Examples:
        terminal-bench -> terminal_bench
        terminal-bench@2.0 -> terminal_bench_2_0
        aime -> aime
        swe-lancer-diamond@all -> swe_lancer_diamond_all
    """
    return dataset_name_version.replace("-", "_").replace("@", "_").replace(".", "_")


def generate_tasks_content(registry: list) -> str:
    """Generate the content of tasks.py from the registry."""
    functions = []
    seen_datasets = set()
    seen_versioned_datasets = set()

    # Registry is an array of benchmark objects
    for dataset in sorted(
        registry, key=lambda d: (d.get("name", ""), d.get("version", ""))
    ):
        dataset_name = dataset.get("name")
        version = dataset.get("version")

        if not dataset_name:
            continue

        description = dataset.get(
            "description", f"{dataset_name} dataset from Harbor registry"
        )

        # Create versioned function (e.g., terminal_bench_2_0 for terminal-bench@2.0)
        if version:
            dataset_name_version = f"{dataset_name}@{version}"
            if dataset_name_version not in seen_versioned_datasets:
                seen_versioned_datasets.add(dataset_name_version)
                func_name = dataset_name_to_function_name(dataset_name_version)

                function_code = TASK_FUNCTION_TEMPLATE.format(
                    func_name=func_name,
                    description=description,
                    dataset_name=dataset_name_version,
                    dataset_name_version=dataset_name_version,
                    version_info=f"Version: {version}",
                )
                functions.append(function_code)

        # Also create unversioned function for latest/default version
        if dataset_name not in seen_datasets:
            seen_datasets.add(dataset_name)
            func_name = dataset_name_to_function_name(dataset_name)
            version_text = (
                f"Latest available ({version} when generated)" if version else "unknown"
            )

            function_code = TASK_FUNCTION_TEMPLATE.format(
                func_name=func_name,
                description=description,
                dataset_name=dataset_name,
                dataset_name_version=dataset_name,
                version_info=f"Version: {version_text}",
            )
            functions.append(function_code)

    return TASKS_TEMPLATE.format(
        timestamp=datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC"),
        registry_url=REGISTRY_URL,
        functions="".join(functions),
    )


def main():
    """Main entry point."""
    print("Harbor Registry Task Generator")
    print("=" * 50)

    # Fetch registry
    registry = fetch_registry()
    print(f"Found {len(registry)} datasets")

    # Generate tasks.py
    print("\nGenerating tasks.py...")
    tasks_content = generate_tasks_content(registry)
    TASKS_FILE.parent.mkdir(parents=True, exist_ok=True)
    TASKS_FILE.write_text(tasks_content)
    print(f"✓ Generated: {TASKS_FILE}")
    print(f"  Size: {len(tasks_content)} bytes")
    print(
        f"  Functions: {len([line for line in tasks_content.split('\n') if line.startswith('@task')])}"
    )


if __name__ == "__main__":
    main()
