#!/usr/bin/env python3
"""Generate static task functions from Harbor registry.

This script fetches the Harbor registry and generates _tasks.py with all
dataset-specific task functions.
"""

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any, Callable

import yaml
from _http import curl_get

REGISTRY_URL = "https://raw.githubusercontent.com/laude-institute/harbor/refs/heads/main/registry.json"
REGISTRY_SITE_BASE = "https://registry.harborframework.com"
REGISTRY_SITE_MAX_PAGES = 20
TASKS_FILE = Path(__file__).parent.parent / "src" / "inspect_harbor" / "_tasks.py"
REGISTRY_YML_FILE = Path(__file__).parent.parent / "docs" / "registry-listing.yml"
OVERRIDES_FILE = Path(__file__).parent.parent / "docs" / "overrides.yml"
# Per-benchmark landing pages. One .qmd per versioned dataset, linked from
# the registry listing. Wiped and regenerated on every run; don't hand-edit.
REGISTRY_PAGES_DIR = Path(__file__).parent.parent / "docs" / "registry"
# Cache for the Harbor registry JSON and scraped org map. Speeds up the
# Quarto pre-render during `quarto preview` (otherwise every reload would
# re-download ~13MB + scrape multiple pages). Cleared by deleting the dir.
CACHE_DIR = Path(__file__).parent.parent / ".cache" / "harbor-registry"
CACHE_TTL_SECONDS = 10 * 60  # 10 minutes


def _cached(
    cache_name: str, fetch: Callable[[], bytes], ttl: int = CACHE_TTL_SECONDS
) -> bytes:
    """Read `cache_name` from CACHE_DIR if fresh, else call `fetch` and write.

    The cache is strictly a local-dev accelerator for preview reloads; CI
    should start from a cold cache each run, which it does naturally because
    nothing persists CACHE_DIR across jobs.
    """
    import time

    path = CACHE_DIR / cache_name
    if path.exists():
        age = time.time() - path.stat().st_mtime
        if age < ttl:
            return path.read_bytes()
    data = fetch()
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return data


def _write_if_changed(path: Path, content: str) -> bool:
    """Write `content` to `path` only if it differs from what's there.

    Stable mtimes matter a lot for `quarto preview`: touching a .qmd file
    (even with identical content) causes Quarto to re-render it and any
    page that references it. Returns True iff the file was written.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == content:
        return False
    path.write_text(content)
    return True


TASKS_TEMPLATE = '''"""Harbor registry dataset tasks.

This file is auto-generated by scripts/generate_tasks.py.
Do not edit manually.

Registry: {registry_url}
"""

from inspect_ai import Task, task

from inspect_harbor._harbor.task import harbor as _harbor_base

{functions}
'''
TASK_FUNCTION_TEMPLATE = '''
@task
def {func_name}(
    dataset_task_names: list[str] | None = None,
    dataset_exclude_task_names: list[str] | None = None,
    n_tasks: int | None = None,
    overwrite_cache: bool = False,
    sandbox_env_name: str = "docker",
    override_cpus: int | None = None,
    override_memory_mb: int | None = None,
    override_gpus: int | None = None,
) -> Task:
    r"""{description}

    Dataset: {dataset_name}
    {version_info}
    Harbor URL: {harbor_url}
    """
    return _harbor_base(
        dataset_name_version="{dataset_name_version}",
        dataset_task_names=dataset_task_names,
        dataset_exclude_task_names=dataset_exclude_task_names,
        n_tasks=n_tasks,
        overwrite_cache=overwrite_cache,
        sandbox_env_name=sandbox_env_name,
        override_cpus=override_cpus,
        override_memory_mb=override_memory_mb,
        override_gpus=override_gpus,
    )
'''

# Header for the generated listing data file. registry.qmd itself is
# hand-maintained; only registry-listing.yml is regenerated.
REGISTRY_YML_HEADER = f"""# This file is auto-generated by scripts/generate_tasks.py. Do not edit manually.
#
# Feeds the Quarto listing on docs/registry.qmd.
#
# Source of truth: {REGISTRY_URL}
# Categories: docs/overrides.yml (hand-maintained; see file header)
"""


def _default_description(dataset_name: str) -> str:
    """Fallback used when the Harbor registry entry has no `description`."""
    return f"{dataset_name} dataset from Harbor registry"


def shorten_urls_in_text(text: str) -> str:
    """Replace long URLs in text with short [link] markdown links.

    Examples:
        "See (https://example.com)" -> "See ([link](https://example.com))"
        "Visit https://example.com for more" -> "Visit [link](https://example.com) for more"
    """
    # Pattern to match URLs (http:// or https://)
    url_pattern = r"(https?://[^\s\)]+)"

    def replace_url(match: re.Match[str]) -> str:
        url = match.group(1)
        return f"[link]({url})"

    return re.sub(url_pattern, replace_url, text)


def fetch_registry() -> list[dict[str, Any]]:
    """Fetch the Harbor registry JSON.

    `file://` URLs are handled locally (used by tests to feed a cached
    registry); HTTP(S) URLs go through the shared curl helper.
    """
    print(f"Fetching registry from {REGISTRY_URL}...")

    if REGISTRY_URL.startswith("file://"):
        path = REGISTRY_URL.removeprefix("file://")
        return json.loads(Path(path).read_text())

    data = _cached("registry.json", lambda: curl_get(REGISTRY_URL))
    return json.loads(data.decode())


def fetch_org_map() -> dict[str, str]:
    """Scrape the public registry site to build a dataset-slug → org-slug map.

    The Harbor registry website (`registry.harborframework.com`) owns the
    canonical dataset-to-org mapping; the JSON registry we fetch does not
    expose an org field. Paginating `/datasets?page=N` yields every public
    dataset as `/datasets/<org>/<name>` anchors.

    Failures in `curl_get` exit the script (via SystemExit) so we never
    silently emit all-fallback URLs.
    """
    print(f"Scraping org map from {REGISTRY_SITE_BASE}/datasets...")
    mapping: dict[str, str] = {}
    href_pattern = re.compile(r'href="/datasets/([a-z0-9-]+)/([a-z0-9-]+)"')
    pages_scraped = 0

    for page in range(1, REGISTRY_SITE_MAX_PAGES + 1):
        url = f"{REGISTRY_SITE_BASE}/datasets?page={page}"
        body = _cached(
            f"org-map-page-{page}.html",
            lambda url=url: curl_get(url, max_time=60),
        ).decode()
        pages_scraped = page
        pairs = set(href_pattern.findall(body))
        new = 0
        for org, name in pairs:
            if name not in mapping:
                mapping[name] = org
                new += 1
        if new == 0:
            break

    print(f"  Mapped {len(mapping)} datasets across {pages_scraped} page(s)")
    return mapping


def build_harbor_url(dataset_name: str, org_map: dict[str, str]) -> tuple[str, bool]:
    """Build a link to the dataset's page on the new Harbor registry site.

    Returns (url, is_canonical). `is_canonical=False` means we fell back to
    the site's search URL because we could not resolve an org for this
    dataset — typically because Harbor has renamed or not yet published it.

    We always link to the dataset's `latest` revision rather than the exact
    registry version string. The site normalizes versions inconsistently
    (e.g. strips trailing `.0`), so registry versions like `1.0` or `2.0` do
    not resolve as path segments; `latest` always does.

    Registry names come in two shapes:
        - plain (e.g. `ade-bench`): org looked up in `org_map`
        - slash-prefixed (e.g. `scale-ai/swe-atlas-qna`): org is the prefix
    """
    if "/" in dataset_name:
        prefix_org, short = dataset_name.split("/", 1)
        return (
            f"{REGISTRY_SITE_BASE}/datasets/{prefix_org}/{short}/latest",
            True,
        )

    # Exact site-slug match
    if dataset_name in org_map:
        return (
            f"{REGISTRY_SITE_BASE}/datasets/{org_map[dataset_name]}/{dataset_name}/latest",
            True,
        )

    # Registry sometimes uses underscores where the site uses hyphens
    # (e.g. arc_agi_2 on our side vs arc-agi-2 on the site).
    normalized = dataset_name.replace("_", "-")
    if normalized in org_map:
        return (
            f"{REGISTRY_SITE_BASE}/datasets/{org_map[normalized]}/{normalized}/latest",
            True,
        )

    # Harbor has likely renamed or not yet published this dataset.
    # Per project decision: fall back to the search URL with the bare
    # dataset name (version suffixes don't help the search).
    return (
        f"{REGISTRY_SITE_BASE}/datasets?q={dataset_name}",
        False,
    )


def dataset_name_to_function_name(dataset_name_version: str) -> str:
    """Convert dataset name or name@version to valid Python function name.

    Examples:
        terminal-bench -> terminal_bench
        terminal-bench@2.0 -> terminal_bench_2_0
        aime -> aime
        swe-lancer-diamond@all -> swe_lancer_diamond_all
        scale-ai/swe-atlas-qna@1.0 -> scale_ai_swe_atlas_qna_1_0
    """
    return (
        dataset_name_version.replace("-", "_")
        .replace("@", "_")
        .replace(".", "_")
        .replace("/", "_")
    )


def generate_tasks_content(
    registry: list[dict[str, Any]], org_map: dict[str, str]
) -> str:
    """Generate the content of _tasks.py from the registry."""
    functions = []
    seen_datasets = set()
    seen_versioned_datasets = set()

    # Registry is an array of benchmark objects
    for dataset in sorted(
        registry, key=lambda d: (d.get("name", ""), d.get("version", ""))
    ):
        dataset_name = dataset.get("name")
        version = dataset.get("version")

        if not dataset_name:
            continue

        description = dataset.get("description", _default_description(dataset_name))
        harbor_url, _ = build_harbor_url(dataset_name, org_map)

        # Create versioned function (e.g., terminal_bench_2_0 for terminal-bench@2.0)
        if version:
            dataset_name_version = f"{dataset_name}@{version}"
            if dataset_name_version not in seen_versioned_datasets:
                seen_versioned_datasets.add(dataset_name_version)
                func_name = dataset_name_to_function_name(dataset_name_version)

                function_code = TASK_FUNCTION_TEMPLATE.format(
                    func_name=func_name,
                    description=description,
                    dataset_name=dataset_name_version,
                    dataset_name_version=dataset_name_version,
                    version_info=f"Version: {version}",
                    harbor_url=harbor_url,
                )
                functions.append(function_code)

        # Also create unversioned function for latest/default version
        if dataset_name not in seen_datasets:
            seen_datasets.add(dataset_name)
            func_name = dataset_name_to_function_name(dataset_name)
            version_text = (
                f"Latest available ({version} when generated)" if version else "unknown"
            )

            function_code = TASK_FUNCTION_TEMPLATE.format(
                func_name=func_name,
                description=description,
                dataset_name=dataset_name,
                dataset_name_version=dataset_name,
                version_info=f"Version: {version_text}",
                harbor_url=harbor_url,
            )
            functions.append(function_code)

    return TASKS_TEMPLATE.format(
        registry_url=REGISTRY_URL,
        functions="\n".join(functions),
    )


def _clean_registry_description(description: str) -> str:
    """Flatten whitespace and strip inline URLs from a registry description.

    The raw registry descriptions contain `Original benchmark: <url>` footers
    and parenthesized URLs that are noise in a short table cell. The listing
    page still carries a link to the Harbor dataset (via `path`), so stripping
    these leaves the description as a single clean sentence.
    """
    description = description.replace("\n", " ").strip()
    # Strip "Original benchmark:", "Adapter:", "Source:", "Website:" footers.
    description = re.sub(
        r"\s*(Original benchmark|Adapter details|Adapter|Source|Website)"
        r":\s*https?://\S+\.?\s*",
        " ",
        description,
    )
    # Eat any leading whitespace alongside the parens so "X (URL)." → "X."
    # rather than "X ."
    description = re.sub(r"\s*\(https?://\S+\)", "", description)
    description = re.sub(r"\s*https?://\S+", "", description)
    description = re.sub(r"\s{2,}", " ", description)
    result = description.strip().rstrip(" .")
    return (result + ".") if result else ""


def load_overrides() -> dict[str, dict[str, Any]]:
    """Load the hand-maintained per-dataset overrides from docs/overrides.yml.

    Returns a mapping of `{dataset_name: {field: value, ...}}`. We only use
    the `categories` field ourselves, but the full entry is returned so
    callers can inspect (e.g. to detect blank-stub entries).
    """
    if not OVERRIDES_FILE.exists():
        print(
            f"  ⚠ {OVERRIDES_FILE} not found. Listing will render "
            f"without category filters.",
            file=sys.stderr,
        )
        return {}
    try:
        data = yaml.safe_load(OVERRIDES_FILE.read_text()) or {}
    except yaml.YAMLError as exc:
        print(
            f"  ⚠ {OVERRIDES_FILE} failed to parse ({exc}). "
            f"Listing will render without category filters.",
            file=sys.stderr,
        )
        return {}
    if not isinstance(data, dict):
        print(
            f"  ⚠ {OVERRIDES_FILE} has unexpected shape (not a mapping). "
            f"Listing will render without category filters.",
            file=sys.stderr,
        )
        return {}
    return {name: fields for name, fields in data.items() if isinstance(fields, dict)}


def append_stub_entries(new_names: list[str]) -> None:
    """Append empty-category stub entries to docs/overrides.yml.

    Called from the nightly cron path when Harbor adds datasets.
    The stub surfaces the missing metadata in the PR diff, and the CI
    validator (scripts/validate_overrides.py) blocks merging until a human
    fills `categories:` in. Appending (rather than alphabetical insertion)
    keeps the existing file formatting and comments intact; reviewers can
    move the entry into sort order when they fill it in.
    """
    if not new_names:
        return
    if not OVERRIDES_FILE.exists():
        print(
            f"  ⚠ Cannot stub missing entries: {OVERRIDES_FILE} does not exist.",
            file=sys.stderr,
        )
        return
    existing = OVERRIDES_FILE.read_text()
    # Ensure we end on a single trailing newline before appending.
    if not existing.endswith("\n"):
        existing += "\n"

    stub_lines = [
        "",
        "# === auto-stubbed by scripts/generate_tasks.py ===",
        "# New datasets added to the Harbor registry that have no override entry.",
        "# Fill in `categories:` (see vocabulary in this file's header) before",
        "# merging: validate_overrides.py will fail CI until you do.",
        "",
    ]
    for name in new_names:
        stub_lines.append(f"{name}:")
        stub_lines.append("  categories: []  # TODO")
        stub_lines.append("")

    OVERRIDES_FILE.write_text(existing + "\n".join(stub_lines))


def resolve_categories(
    registry: list[dict[str, Any]], overrides: dict[str, dict[str, Any]]
) -> tuple[dict[str, list[str]], list[str]]:
    """Build the dataset→categories map and auto-stub any missing entries.

    Returns `(categories_map, newly_stubbed_names)`. The caller uses the map
    to populate the listing entries and the list of newly-stubbed names to
    write back warnings (and drive the PR body in CI).
    """
    categories_map: dict[str, list[str]] = {}
    new_names: list[str] = []
    seen_registry_names: set[str] = set()

    for entry in registry:
        name = entry.get("name")
        if not name or name in seen_registry_names:
            continue
        seen_registry_names.add(name)

        ov = overrides.get(name)
        if ov is None:
            new_names.append(name)
            continue

        cats = ov.get("categories")
        if isinstance(cats, list) and all(isinstance(c, str) for c in cats):
            categories_map[name] = list(cats)

    if new_names:
        new_names.sort()
        print(
            f"\n⚠ {len(new_names)} registry dataset(s) have no override entry "
            f"in docs/overrides.yml and were auto-stubbed:",
            file=sys.stderr,
        )
        for n in new_names:
            print(f"  - {n}", file=sys.stderr)
        print(
            "\n  Fill in `categories:` for each before merging. "
            "scripts/validate_overrides.py will block merges on empty stubs.",
            file=sys.stderr,
        )
        append_stub_entries(new_names)

    return categories_map, new_names


def generate_registry_yml_content(
    registry: list[dict[str, Any]],
    org_map: dict[str, str],
    categories_map: dict[str, list[str]],
) -> str:
    """Build docs/registry-listing.yml — the data source for the Quarto listing.

    One entry per versioned dataset. `path` points to the internal
    per-benchmark page (generated separately by `generate_registry_pages`).
    `categories` is omitted when we have no override entry for the dataset.
    """
    entries: list[dict[str, Any]] = []
    seen_versioned_datasets: set[str] = set()
    fallback_datasets: list[str] = []

    for dataset in sorted(
        registry, key=lambda d: (d.get("name", ""), d.get("version", ""))
    ):
        dataset_name = dataset.get("name")
        version = dataset.get("version")
        if not dataset_name or not version:
            continue
        description = dataset.get("description", _default_description(dataset_name))
        tasks = dataset.get("tasks", [])
        num_samples = len(tasks)

        dataset_name_version = f"{dataset_name}@{version}"
        if dataset_name_version in seen_versioned_datasets:
            continue
        seen_versioned_datasets.add(dataset_name_version)

        func_name = dataset_name_to_function_name(dataset_name_version)
        # Resolve canonical-vs-fallback once so we can surface a single
        # aggregated warning below; the URL itself is used by the per-page
        # generator, not in the listing row.
        _, is_canonical = build_harbor_url(dataset_name, org_map)
        if not is_canonical:
            fallback_datasets.append(dataset_name_version)

        # path: internal per-benchmark page (generated by generate_registry_pages).
        # The Harbor registry URL moves to the metadata table on that page, which
        # is also the destination Harbor's mini-pages should now link to.
        entry: dict[str, Any] = {
            "title": dataset_name_version,
            "path": f"registry/{func_name}.html",
            "description": _clean_registry_description(description),
            "task_function": func_name,
            "samples": num_samples,
            "version": version,
        }
        cats = categories_map.get(dataset_name)
        if cats:
            entry["categories"] = cats
        entries.append(entry)

    if fallback_datasets:
        print(
            f"\n⚠ {len(fallback_datasets)} dataset(s) could not be resolved "
            f"to an org on {REGISTRY_SITE_BASE} and fell back to the search URL:",
            file=sys.stderr,
        )
        for d in fallback_datasets:
            print(f"  - {d}", file=sys.stderr)

    body = yaml.safe_dump(
        entries,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=10000,
    )
    return REGISTRY_YML_HEADER + "\n" + body


# Per-page `categories:` render as pill-style tags under the page title
# and link back to the listing filtered by that category.
PAGE_TEMPLATE = """---
title: "{title}"
description: |
  {description}
{categories_block}---

[← Back to Registry](../registry.qmd)

## Run this task

**CLI:**

```bash
inspect eval inspect_harbor/{func_name} --model openai/gpt-5
```

**Python:**

```python
from inspect_ai import eval
from inspect_harbor import {func_name}

eval({func_name}(), model="openai/gpt-5")
```

## Dataset information

| | |
|---|---|
| Harbor registry | [{dataset_name_version}]({harbor_url}) |
| Inspect task    | `{func_name}` |
| Version         | {version} |
| Samples         | {samples} |{optional_rows}

See [Task Parameters](../parameters.qmd) for the parameter set shared across all Harbor tasks.
"""


def _render_page(
    dataset_name_version: str,
    version: str,
    func_name: str,
    description: str,
    samples: int,
    harbor_url: str,
    categories: list[str],
    override: dict[str, Any],
) -> str:
    """Render the .qmd body for a single per-benchmark page."""
    # Render frontmatter categories as a YAML block list. Empty string
    # (not `categories: []`) when no categories, so the frontmatter
    # doesn't carry an empty key.
    categories_block = (
        "categories:\n" + "\n".join(f"  - {c}" for c in categories) + "\n"
        if categories
        else ""
    )

    optional: list[str] = []
    arxiv = override.get("arxiv")
    repo = override.get("repo")
    if isinstance(arxiv, str) and arxiv:
        optional.append(f"| Paper           | [arxiv]({arxiv}) |")
    if isinstance(repo, str) and repo:
        # Keep the label terse; the URL host is enough for a reader to scan.
        optional.append(f"| Source          | [{repo}]({repo}) |")
    # Prepend the newline so the template can attach `{optional_rows}`
    # directly after the last required row without introducing a blank
    # line when there are no optional rows.
    optional_rows = ("\n" + "\n".join(optional)) if optional else ""

    return PAGE_TEMPLATE.format(
        title=dataset_name_version,
        description=description,
        categories_block=categories_block,
        func_name=func_name,
        dataset_name_version=dataset_name_version,
        harbor_url=harbor_url,
        version=version,
        samples=samples,
        optional_rows=optional_rows,
    )


def generate_registry_pages(
    registry: list[dict[str, Any]],
    org_map: dict[str, str],
    overrides: dict[str, dict[str, Any]],
    categories_map: dict[str, list[str]],
) -> int:
    """Write per-benchmark landing pages under docs/registry/.

    Returns the number of pages written this invocation (i.e. the number
    whose content actually changed + any newly-created ones). Uses
    `_write_if_changed` so unchanged pages keep their mtimes, which is
    critical for `quarto preview`: touching a .qmd on every pre-render
    would make Quarto re-render all 80 pages on every reload.

    Orphan pages (for datasets no longer in the registry) are deleted.
    """
    REGISTRY_PAGES_DIR.mkdir(parents=True, exist_ok=True)

    seen_versioned_datasets: set[str] = set()
    expected_files: set[Path] = set()
    written = 0

    for dataset in sorted(
        registry, key=lambda d: (d.get("name", ""), d.get("version", ""))
    ):
        dataset_name = dataset.get("name")
        version = dataset.get("version")
        if not dataset_name or not version:
            continue

        dataset_name_version = f"{dataset_name}@{version}"
        if dataset_name_version in seen_versioned_datasets:
            continue
        seen_versioned_datasets.add(dataset_name_version)

        func_name = dataset_name_to_function_name(dataset_name_version)
        description = _clean_registry_description(
            dataset.get("description", _default_description(dataset_name))
        )
        samples = len(dataset.get("tasks", []) or [])
        harbor_url, _ = build_harbor_url(dataset_name, org_map)
        categories = categories_map.get(dataset_name, [])
        override = overrides.get(dataset_name, {})

        content = _render_page(
            dataset_name_version=dataset_name_version,
            version=str(version),
            func_name=func_name,
            description=description,
            samples=samples,
            harbor_url=harbor_url,
            categories=categories,
            override=override,
        )

        page_path = REGISTRY_PAGES_DIR / f"{func_name}.qmd"
        expected_files.add(page_path)
        if _write_if_changed(page_path, content):
            written += 1

    # Delete any .qmd that shouldn't be there (dataset removed upstream).
    for stale in REGISTRY_PAGES_DIR.glob("*.qmd"):
        if stale not in expected_files:
            stale.unlink()

    return written


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate inspect_harbor task bindings and docs artifacts "
        "from the Harbor registry.",
    )
    parser.add_argument(
        "--docs-only",
        action="store_true",
        help="Skip regenerating src/inspect_harbor/_tasks.py and only emit "
        "the docs artifacts (registry-listing.yml + registry/*.qmd, plus "
        "auto-stubs into overrides.yml). Used by Quarto's pre-render so "
        "local docs builds don't churn _tasks.py.",
    )
    args = parser.parse_args()

    print("Harbor Registry Task Generator")
    print("=" * 50)

    # Fetch registry
    registry = fetch_registry()
    print(f"Found {len(registry)} datasets")

    # Scrape the new Harbor registry site for the dataset→org mapping needed
    # to build working documentation links (embedded in _tasks.py docstrings
    # and in the registry.qmd table).
    org_map = fetch_org_map()

    if not args.docs_only:
        # Generate _tasks.py
        print("\nGenerating _tasks.py...")
        tasks_content = generate_tasks_content(registry, org_map)
        changed = _write_if_changed(TASKS_FILE, tasks_content)
        print(f"{'✓ Wrote' if changed else '= Unchanged'}: {TASKS_FILE}")
        print(f"  Size: {len(tasks_content)} bytes")
        print(
            f"  Functions: {len([line for line in tasks_content.split('\n') if line.startswith('@task')])}"
        )
    else:
        print("\nSkipping _tasks.py regeneration (--docs-only).")

    # Load hand-maintained overrides and auto-stub any new datasets. This
    # always succeeds so the nightly PR still gets opened; CI validation
    # (scripts/validate_overrides.py) is the gate that blocks merging when
    # the stubs haven't been filled in.
    print(f"\nLoading overrides from {OVERRIDES_FILE}...")
    overrides = load_overrides()
    categories_map, newly_stubbed = resolve_categories(registry, overrides)
    print(f"  Loaded categories for {len(categories_map)} dataset(s)")
    if newly_stubbed:
        print(f"  Auto-stubbed {len(newly_stubbed)} new dataset(s) in {OVERRIDES_FILE}")

    # Generate docs/registry-listing.yml (data source for the Quarto listing
    # in docs/registry.qmd, which is itself hand-maintained)
    print("\nGenerating docs/registry-listing.yml...")
    registry_yml_content = generate_registry_yml_content(
        registry, org_map, categories_map
    )
    changed = _write_if_changed(REGISTRY_YML_FILE, registry_yml_content)
    print(f"{'✓ Wrote' if changed else '= Unchanged'}: {REGISTRY_YML_FILE}")
    print(f"  Size: {len(registry_yml_content)} bytes")

    # Generate per-benchmark landing pages under docs/registry/
    print(f"\nGenerating per-benchmark pages in {REGISTRY_PAGES_DIR}...")
    pages_written = generate_registry_pages(
        registry, org_map, overrides, categories_map
    )
    if pages_written:
        print(f"✓ Wrote {pages_written} page(s) (others unchanged)")
    else:
        print("= All pages unchanged")


if __name__ == "__main__":
    main()
